server {
    listen 80;
    listen [::]:80;
    server_name gustavoemalucasam.net.br;

    root /var/www/casamento/current;

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        return 503;
    }
}